apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: redis-queue
spec:
  host: redis-queue
  subsets:
    - name: v1
      labels:
        version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-queue
spec:
  hosts:
    - redis-queue
  http:
    - route:
        - destination:
            host: redis-queue
            subset: v1
        weight: 100