apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microapp
spec:
  destination:
    namespace: laboratorio
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/k8s/
    repoURL: 'https://github.com/DevOPS-ATA/microservice-app-example.git'
    targetRevision: master
    directory:
      recurse: true
  project: laboratorio
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false