apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: todos-api
spec:
  host: todos-api
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: v1
      labels:
        version: v1