apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: microapp-cert-ingress
spec:
  secretName: microapp-cert-ingress
  dnsNames:
    - "microapp-istio.ibmcloud.ingeniamos.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer