apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: microdemo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
    - "*"
  gateways:
    - microdemo-gateway
  http:
      route:
        - destination:
            host: frontend
            port:
              number: 8080